### ISSUE TITLE
[FEATURE] 냉장고 속 식재료를 관리하는 기능

### ISSUE THREAD

**Issue by younghyun-na** [weekly-academy/fridge-friend#6]
## Description
냉장고에 식재료를 등록하여 냉장고 속 식재료를 관리하는 기능이다.

## Todo
- [ ] 냉장고에 식재료를 등록하는 기능
- [ ] 냉장고에 있는 식재료를 조회하는 기능
- [ ] 냉장고에 있는 식재료의 정보를 수정하는 기능
- [ ] 냉장고에 있는 식재료를 삭제하는 기능
